<# 
.SYNOPSIS
    Loads coverage analysis data from Step 2 (analyze-coverage)
.DESCRIPTION
    Reads coverage-analysis.json generated by analyze-coverage skill.
    Contains coverage metrics, risk scores, edge cases, and uncovered methods.
    
    This provides a clear contract between analyze-coverage and plan-tests skills,
    ensuring data is persisted and available across Copilot sessions.
.PARAMETER AnalysisPath
    Path to coverage-analysis.json. Defaults to ./TestResults/coverage-analysis.json
.EXAMPLE
    .\Load-CoverageAnalysis.ps1
.NOTES
    Author: AI Unit Test Generator
    Dependencies: None (reads JSON file created by analyze-coverage)
    Data Source: coverage-analysis.json
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [string]$AnalysisPath = "./TestResults/coverage-analysis.json"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "`n?? Loading Coverage Analysis..." -ForegroundColor Cyan

# ============================================================
# Step 1: Validate File Exists
# ============================================================

if (-not (Test-Path $AnalysisPath)) {
    throw @"
ERROR: Coverage analysis file not found at: $AnalysisPath

This file should be created by analyze-coverage skill (Step 2).
Ensure the workflow is executed in order:
  1. scan-repository
  2. analyze-coverage ? Creates coverage-analysis.json
  3. plan-tests ? Reads coverage-analysis.json (you are here)
  
Run analyze-coverage skill first.
"@
}

# ============================================================
# Step 2: Load and Parse JSON
# ============================================================

try {
    $analysisContent = Get-Content $AnalysisPath -Raw
    $analysis = $analysisContent | ConvertFrom-Json
    
    Write-Host "? Coverage analysis loaded from: $AnalysisPath" -ForegroundColor Green
} catch {
    throw "ERROR: Failed to parse coverage-analysis.json. File may be corrupted. Error: $($_.Exception.Message)"
}

# ============================================================
# Step 3: Validate Required Fields
# ============================================================

$requiredFields = @(
    'baseline',
    'target',
    'gap',
    'riskScores',
    'uncoveredMethods',
    'partiallyTestedMethods',
    'edgeCases',
    'riskAssessment'
)

$missingFields = $requiredFields | Where-Object { -not $analysis.PSObject.Properties.Name.Contains($_) }

if ($missingFields.Count -gt 0) {
    throw "ERROR: Coverage analysis missing required fields: $($missingFields -join ', ')"
}

Write-Host "? All required fields present" -ForegroundColor Green

# ============================================================
# Step 4: Display Summary
# ============================================================

Write-Host ""
Write-Host "?? Coverage Baseline:" -ForegroundColor White
Write-Host "   Line: $($analysis.baseline.lineCoverage)%" -ForegroundColor Gray
Write-Host "   Branch: $($analysis.baseline.branchCoverage)%" -ForegroundColor Gray
Write-Host "   Method: $($analysis.baseline.methodCoverage)%" -ForegroundColor Gray
Write-Host "   Full Method: $($analysis.baseline.fullMethodCoverage)%" -ForegroundColor Gray

Write-Host ""
Write-Host "?? Risk Assessment:" -ForegroundColor White
Write-Host "   Critical: $($analysis.riskAssessment.critical.Count) methods" -ForegroundColor Red
Write-Host "   High: $($analysis.riskAssessment.high.Count) methods" -ForegroundColor Yellow
Write-Host "   Medium: $($analysis.riskAssessment.medium.Count) methods" -ForegroundColor Cyan
Write-Host "   Low: $($analysis.riskAssessment.low.Count) methods" -ForegroundColor Green

Write-Host ""
Write-Host "?? Estimated Tests: $($analysis.estimatedTestsNeeded)" -ForegroundColor White
Write-Host ""

# ============================================================
# Step 5: Return Analysis Object
# ============================================================

return $analysis
